import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "@/globals.css";
import Navbar from "@/_components/Navbar";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} antialiased container mx-auto`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
